#include <tinyvm/isa_v1.h>

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static void fail(const char *message){fprintf(stderr,"ISA v1 conformance failed: %s\n",message);exit(1);}
static void id(char out[64],const char *value){snprintf(out,64,"%s",value);}
static void provenance(TinyvmProvenance *items,size_t count){for(size_t i=0;i<count;++i){items[i].instruction=i;items[i].operation=i+1;items[i].block=1;items[i].line=(uint32_t)(i+1);items[i].column=1;id(items[i].source,"isa-v1-source");id(items[i].derivation,"isa-v1-lowering");}}
static TinyvmArtifactV2 artifact(InstrWord *code,size_t code_count,TinyvmConstant *constants,size_t constant_count,TinyvmProvenance *prov,size_t slots){TinyvmArtifactV2 a;tinyvm_artifact_v2_init(&a);a.isa_version=1;a.data_words=slots;a.stack_words=16;id(a.artifact_id,"isa-v1-artifact");id(a.source_id,"isa-v1-source");id(a.target_policy_id,"tinyvm-portable");id(a.lowering_plan_id,"isa-v1-plan");id(a.optimization_id,"isa-v1-optimization");a.code=code;a.code_count=code_count;a.constants=constants;a.constant_count=constant_count;a.provenance=prov;a.provenance_count=code_count;return a;}
static bool same_value(const TinyvmValue *a,const TinyvmValue *b){return a->carrier==b->carrier&&a->bits==b->bits&&a->initialized==b->initialized;}
static bool same_fault(const char *a,const char *b){return (!a||!b)?a==b:strcmp(a,b)==0;}
static bool same_context(const TinyvmIsaV1Context *a,const TinyvmIsaV1Context *b){if(a->slot_count!=b->slot_count||a->pc!=b->pc||a->steps!=b->steps||a->running!=b->running||a->returned!=b->returned||a->trap!=b->trap||a->trap_instruction!=b->trap_instruction||a->argument_count!=b->argument_count||a->arguments!=b->arguments||!same_value(&a->result,&b->result)||!same_fault(a->fault,b->fault))return false;for(size_t i=0;i<a->slot_count;++i)if(!same_value(&a->slots[i],&b->slots[i]))return false;return true;}
static TinyvmIsaV1Context execute(const TinyvmArtifactV2 *a,uint64_t limit,bool expected){char diagnostic[160];if(!tinyvm_artifact_v2_validate(a,diagnostic,sizeof diagnostic))fail(diagnostic);TinyvmIsaV1Context ctx,computed;if(!tinyvm_isa_v1_context_init(&ctx,(size_t)a->data_words,limit)||!tinyvm_isa_v1_context_init(&computed,(size_t)a->data_words,limit))fail("context allocation");bool result=tinyvm_isa_v1_run_switch(a,&ctx),computed_result=tinyvm_isa_v1_run_computed(a,&computed);if(result!=expected||computed_result!=expected)fail("unexpected execution result");if(!same_context(&ctx,&computed))fail("switch/computed engine divergence");tinyvm_isa_v1_context_destroy(&computed);return ctx;}

static void arithmetic_and_control(void){
    TinyvmConstant c[]={{1,TINYVM_CARRIER_I32,20},{2,TINYVM_CARRIER_I32,22},{3,TINYVM_CARRIER_I32,42}};
    InstrWord code[]={{TV1_CONST,0,1,0},{TV1_CONST,1,2,0},{TV1_ADD,2,0,1},{TV1_CONST,3,3,0},{TV1_CMP_EQ,4,2,3},{TV1_BRANCH,4,7,6},{TV1_TRAP,99,0,0},{TV1_CONVERT,5,2,TINYVM_CARRIER_I64},{TV1_MOVE,6,5,0},{TV1_RETURN,6,0,0}};
    TinyvmProvenance p[10]={0};provenance(p,10);TinyvmArtifactV2 a=artifact(code,10,c,3,p,7);TinyvmIsaV1Context ctx=execute(&a,100,true);if(!ctx.returned||ctx.result.carrier!=TINYVM_CARRIER_I64||ctx.result.bits!=42)fail("arithmetic/control result");tinyvm_isa_v1_context_destroy(&ctx);
}
static void more_arithmetic(void){
    TinyvmConstant c[]={{1,TINYVM_CARRIER_I64,100},{2,TINYVM_CARRIER_I64,4}};
    InstrWord code[]={{TV1_CONST,0,1,0},{TV1_CONST,1,2,0},{TV1_SUB,2,0,1},{TV1_MUL,3,2,1},{TV1_SDIV,4,3,1},{TV1_CMP_GE,5,4,2},{TV1_RETURN,4,0,0}};
    TinyvmProvenance p[7]={0};provenance(p,7);TinyvmArtifactV2 a=artifact(code,7,c,2,p,6);TinyvmIsaV1Context ctx=execute(&a,100,true);if(ctx.result.carrier!=TINYVM_CARRIER_I64||ctx.result.bits!=96)fail("sub/mul/div result");tinyvm_isa_v1_context_destroy(&ctx);
}
static void comparisons_and_terminals(void){
    TinyvmConstant c[]={{1,TINYVM_CARRIER_I64,4},{2,TINYVM_CARRIER_I64,5},{3,TINYVM_CARRIER_I1,0}};
    InstrWord compare[]={{TV1_CONST,0,1,0},{TV1_CONST,1,2,0},{TV1_CMP_NE,2,0,1},{TV1_CMP_LT,3,0,1},{TV1_CMP_LE,4,0,1},{TV1_CMP_GT,5,1,0},{TV1_CMP_GE,6,1,0},{TV1_RETURN,6,0,0}};TinyvmProvenance pc[8]={0};provenance(pc,8);TinyvmArtifactV2 a=artifact(compare,8,c,3,pc,7);TinyvmIsaV1Context ctx=execute(&a,30,true);if(ctx.result.carrier!=TINYVM_CARRIER_I1||ctx.result.bits!=1)fail("comparison family");tinyvm_isa_v1_context_destroy(&ctx);
    InstrWord branch_false[]={{TV1_CONST,0,3,0},{TV1_BRANCH,0,2,3},{TV1_TRAP,77,0,0},{TV1_HALT,0,0,0}};TinyvmProvenance pb[4]={0};provenance(pb,4);a=artifact(branch_false,4,c,3,pb,1);ctx=execute(&a,20,true);if(ctx.result.carrier!=TINYVM_CARRIER_I32||ctx.result.bits!=0)fail("false branch/halt");tinyvm_isa_v1_context_destroy(&ctx);
    InstrWord nop_halt[]={{TV1_NOP,0,0,0},{TV1_HALT,0,0,0}};TinyvmProvenance pn[2]={0};provenance(pn,2);a=artifact(nop_halt,2,NULL,0,pn,0);ctx=execute(&a,10,true);tinyvm_isa_v1_context_destroy(&ctx);
    InstrWord explicit_trap[]={{TV1_TRAP,55,0,0}};TinyvmProvenance pt[1]={0};provenance(pt,1);a=artifact(explicit_trap,1,NULL,0,pt,0);ctx=execute(&a,10,false);if(ctx.trap!=55)fail("explicit trap code");tinyvm_isa_v1_context_destroy(&ctx);
}
static void handles(void){
    InstrWord code[]={{TV1_STRING_HANDLE,0,1,0},{TV1_STORAGE_HANDLE,1,1,0},{TV1_RETURN,0,0,0}};TinyvmProvenance p[3]={0};provenance(p,3);TinyvmString strings[1]={{1,(uint8_t*)"hello",5}};TinyvmStorage storage[1]={{1,64,8,2}};TinyvmArtifactV2 a=artifact(code,3,NULL,0,p,2);a.strings=strings;a.string_count=1;a.storage=storage;a.storage_count=1;TinyvmIsaV1Context ctx=execute(&a,20,true);if(ctx.result.carrier!=TINYVM_CARRIER_OPAQUE_HANDLE||ctx.result.bits!=UINT64_C(0x0100000000000001))fail("opaque string handle");tinyvm_isa_v1_context_destroy(&ctx);
}
static void expected_traps(void){
    TinyvmConstant c[]={{1,TINYVM_CARRIER_I32,1},{2,TINYVM_CARRIER_I32,0}};
    InstrWord divide[]={{TV1_CONST,0,1,0},{TV1_CONST,1,2,0},{TV1_SDIV,2,0,1},{TV1_RETURN,2,0,0}};TinyvmProvenance pd[4]={0};provenance(pd,4);TinyvmArtifactV2 a=artifact(divide,4,c,2,pd,3);TinyvmIsaV1Context ctx=execute(&a,20,false);if(ctx.trap!=TV1_TRAP_DIVISION_BY_ZERO||ctx.trap_instruction!=2)fail("division trap");tinyvm_isa_v1_context_destroy(&ctx);
    InstrWord uninitialized[]={{TV1_RETURN,0,0,0}};TinyvmProvenance pu[1]={0};provenance(pu,1);a=artifact(uninitialized,1,NULL,0,pu,1);ctx=execute(&a,20,false);if(ctx.trap!=TV1_TRAP_UNINITIALIZED_SLOT)fail("uninitialized trap");tinyvm_isa_v1_context_destroy(&ctx);
    InstrWord loop[]={{TV1_JMP,0,0,0},{TV1_HALT,0,0,0}};TinyvmProvenance pl[2]={0};provenance(pl,2);a=artifact(loop,2,NULL,0,pl,0);ctx=execute(&a,5,false);if(ctx.trap!=TV1_TRAP_STEP_LIMIT)fail("step-limit trap");tinyvm_isa_v1_context_destroy(&ctx);
    TinyvmConstant overflow_constants[]={{1,TINYVM_CARRIER_I32,INT32_MAX},{2,TINYVM_CARRIER_I32,1}};InstrWord overflow[]={{TV1_CONST,0,1,0},{TV1_CONST,1,2,0},{TV1_ADD,2,0,1},{TV1_RETURN,2,0,0}};TinyvmProvenance po[4]={0};provenance(po,4);a=artifact(overflow,4,overflow_constants,2,po,3);ctx=execute(&a,20,true);if(ctx.result.bits!=(uint64_t)(int64_t)INT32_MIN)fail("modular arithmetic result");tinyvm_isa_v1_context_destroy(&ctx);
}
static void unresolved_import(void){
    TinyvmConstant c[]={{1,TINYVM_CARRIER_I32,7}};InstrWord code[]={{TV1_CONST,0,1,0},{TV1_CALL_IMPORT,1,1,0},{TV1_RETURN,1,0,0}};TinyvmProvenance p[3]={0};provenance(p,3);TinyvmImport x[1]={0};x[0].id=1;id(x[0].contract,"libc-abs-v1");id(x[0].library,"libc.so.6");id(x[0].convention,"c");id(x[0].symbol,"abs");id(x[0].effect,"pure");id(x[0].parameters,"c_int");id(x[0].result,"c_int");id(x[0].evidence,"binding-evidence-1");TinyvmArtifactV2 a=artifact(code,3,c,1,p,2);a.imports=x;a.import_count=1;TinyvmIsaV1Context ctx=execute(&a,20,false);if(ctx.trap!=TV1_TRAP_UNRESOLVED_IMPORT)fail("unresolved import trap");tinyvm_isa_v1_context_destroy(&ctx);
}
static bool test_resolver(void *user,const TinyvmArtifactV2 *a,const TinyvmImport *x,const TinyvmValue *arguments,size_t count,TinyvmValue *result,const char **fault){(void)user;(void)a;(void)fault;if(strcmp(x->symbol,"abs")||count!=1||arguments[0].carrier!=TINYVM_CARRIER_I32)return false;int32_t value=(int32_t)arguments[0].bits;if(value<0)value=-value;*result=(TinyvmValue){TINYVM_CARRIER_I32,(uint64_t)(int64_t)value,true};return true;}
static void resolved_import_engines(void){TinyvmConstant c[]={{1,TINYVM_CARRIER_I32,(uint64_t)(int64_t)-7}};InstrWord code[]={{TV1_CONST,0,1,0},{TV1_CALL_IMPORT,1,1,0},{TV1_RETURN,1,0,0}};TinyvmProvenance p[3]={0};provenance(p,3);TinyvmImport x[1]={0};x[0].id=1;id(x[0].contract,"libc");id(x[0].library,"libc.so.6");id(x[0].convention,"c");id(x[0].symbol,"abs");id(x[0].effect,"pure");id(x[0].parameters,"c_int");id(x[0].result,"c_int");id(x[0].evidence,"binding-evidence-1");TinyvmArtifactV2 a=artifact(code,3,c,1,p,2);a.imports=x;a.import_count=1;char diagnostic[160];if(!tinyvm_artifact_v2_validate(&a,diagnostic,sizeof diagnostic))fail(diagnostic);TinyvmIsaV1Context reference,computed;if(!tinyvm_isa_v1_context_init(&reference,2,20)||!tinyvm_isa_v1_context_init(&computed,2,20))fail("resolved import context allocation");reference.import_resolver=test_resolver;computed.import_resolver=test_resolver;if(!tinyvm_isa_v1_run_switch(&a,&reference)||!tinyvm_isa_v1_run_computed(&a,&computed)||!same_context(&reference,&computed)||reference.result.bits!=7)fail("resolved import engine divergence");tinyvm_isa_v1_context_destroy(&reference);tinyvm_isa_v1_context_destroy(&computed);}
static void isa_v2_execution_inputs(void){
    InstrWord code[]={{TV1_RETURN,0,0,0}};TinyvmProvenance p[1]={0};provenance(p,1);TinyvmArtifactV2 a=artifact(code,1,NULL,0,p,4);a.isa_version=2;TinyvmIsaV1Context reference,computed;if(!tinyvm_isa_v1_context_init(&reference,4,20)||!tinyvm_isa_v1_context_init(&computed,4,20))fail("ISA v2 context allocation");const char *arguments[]={"program.tvm","selected","third"};reference.argument_count=3;reference.arguments=arguments;computed.argument_count=3;computed.arguments=arguments;if(!tinyvm_isa_v1_run_switch(&a,&reference)||!tinyvm_isa_v1_run_computed(&a,&computed)||!same_context(&reference,&computed))fail("ISA v2 execution-input engine divergence");if(reference.result.carrier!=TINYVM_CARRIER_I32||reference.result.bits!=3||reference.slots[2].carrier!=TINYVM_CARRIER_OPAQUE_HANDLE||reference.slots[2].bits!=UINT64_C(0x0300000000000001))fail("ISA v2 execution inputs");tinyvm_isa_v1_context_destroy(&reference);tinyvm_isa_v1_context_destroy(&computed);
}
static bool reject_graph_schedule(void *user,const TinyvmArtifactV2 *a,const TinyvmGraphActivationRecord *record,const char **fault){(void)user;(void)a;if(record->identity.activation_id!=7)return false;*fault="test scheduler refusal";return false;}
static void graph_schedule_hook(void){
    InstrWord code[]={{TV1_GRAPH_ACTIVATE,1,-1,0},{TV1_HALT,0,0,0}};TinyvmProvenance p[2]={0};provenance(p,2);
    TinyvmGraphActivation activation={0};activation.id=1;activation.activation_id=7;activation.input_activation_id=UINT64_MAX;activation.output_signal_id=1;id(activation.kind,"startup");id(activation.node_id,"source");id(activation.wire_id,"-");id(activation.input_port,"-");id(activation.output_port,"out");
    TinyvmArtifactV2 a=artifact(code,2,NULL,0,p,1);a.isa_version=2;a.graph_activations=&activation;a.graph_activation_count=1;char diagnostic[160];if(!tinyvm_artifact_v2_validate(&a,diagnostic,sizeof diagnostic))fail(diagnostic);
    TinyvmIsaV1Context reference,computed;if(!tinyvm_isa_v1_context_init(&reference,1,20)||!tinyvm_isa_v1_context_init(&computed,1,20))fail("graph scheduler context allocation");reference.graph_schedule_hook=reject_graph_schedule;computed.graph_schedule_hook=reject_graph_schedule;
    if(tinyvm_isa_v1_run_switch(&a,&reference)||tinyvm_isa_v1_run_computed(&a,&computed)||reference.trap!=TV1_TRAP_EXPLICIT||computed.trap!=TV1_TRAP_EXPLICIT||!same_fault(reference.fault,computed.fault)||strcmp(reference.fault,"test scheduler refusal")||reference.graph_record_count!=1||computed.graph_record_count!=1||reference.graph_records[0].sequence!=0||computed.graph_records[0].identity.activation_id!=7||tinyvm_isa_v1_context_pending_graph_activations(&reference)||tinyvm_isa_v1_context_pending_graph_activations(&computed))fail("graph scheduler hook divergence");
    tinyvm_isa_v1_context_destroy(&reference);tinyvm_isa_v1_context_destroy(&computed);
}
static void graph_record_limit(void){
    InstrWord code[]={{TV1_GRAPH_ACTIVATE,1,-1,0},{TV1_GRAPH_ACTIVATE,2,-1,0},{TV1_HALT,0,0,0}};TinyvmProvenance p[3]={0};provenance(p,3);
    TinyvmGraphActivation activations[2]={0};for(size_t i=0;i<2;++i){activations[i].id=i+1;activations[i].activation_id=i+1;activations[i].input_activation_id=UINT64_MAX;activations[i].output_signal_id=i+1;id(activations[i].kind,"startup");id(activations[i].node_id,"source");id(activations[i].wire_id,"-");id(activations[i].input_port,"-");id(activations[i].output_port,"out");}
    TinyvmArtifactV2 a=artifact(code,3,NULL,0,p,1);a.isa_version=2;a.graph_activations=activations;a.graph_activation_count=2;char diagnostic[160];if(!tinyvm_artifact_v2_validate(&a,diagnostic,sizeof diagnostic))fail(diagnostic);
    TinyvmIsaV1Context reference,computed;if(!tinyvm_isa_v1_context_init(&reference,1,20)||!tinyvm_isa_v1_context_init(&computed,1,20))fail("graph record limit context allocation");if(!tinyvm_isa_v1_context_set_graph_record_limit(&reference,1)||!tinyvm_isa_v1_context_set_graph_record_limit(&computed,1))fail("graph record limit setup");
    if(tinyvm_isa_v1_run_switch(&a,&reference)||tinyvm_isa_v1_run_computed(&a,&computed)||reference.trap!=TV1_TRAP_EXPLICIT||computed.trap!=TV1_TRAP_EXPLICIT||!same_fault(reference.fault,computed.fault)||strcmp(reference.fault,"graph activation record limit exceeded")||reference.trap_instruction!=1||computed.trap_instruction!=1||reference.graph_record_count!=1||computed.graph_record_count!=1)fail("graph record limit divergence");
    tinyvm_isa_v1_context_destroy(&reference);tinyvm_isa_v1_context_destroy(&computed);
}
static void graph_activation_queue(void){
    InstrWord code[]={{TV1_GRAPH_ACTIVATE,1,-1,0},{TV1_GRAPH_ACTIVATE,2,-1,0},{TV1_HALT,0,0,0}};TinyvmProvenance p[3]={0};provenance(p,3);
    TinyvmGraphActivation activations[2]={0};for(size_t i=0;i<2;++i){activations[i].id=i+1;activations[i].activation_id=i+10;activations[i].input_activation_id=UINT64_MAX;activations[i].output_signal_id=i+1;id(activations[i].kind,"startup");id(activations[i].node_id,"source");id(activations[i].wire_id,"-");id(activations[i].input_port,"-");id(activations[i].output_port,"out");}
    TinyvmArtifactV2 a=artifact(code,3,NULL,0,p,1);a.isa_version=2;a.graph_activations=activations;a.graph_activation_count=2;char diagnostic[160];if(!tinyvm_artifact_v2_validate(&a,diagnostic,sizeof diagnostic))fail(diagnostic);
    TinyvmIsaV1Context reference,computed;if(!tinyvm_isa_v1_context_init(&reference,1,20)||!tinyvm_isa_v1_context_init(&computed,1,20))fail("graph activation queue context allocation");if(!tinyvm_isa_v1_context_set_graph_record_limit(&reference,2)||!tinyvm_isa_v1_context_set_graph_record_limit(&computed,2))fail("graph activation queue limit setup");
    if(!tinyvm_isa_v1_run_switch(&a,&reference)||!tinyvm_isa_v1_run_computed(&a,&computed)||tinyvm_isa_v1_context_pending_graph_activations(&reference)!=2||tinyvm_isa_v1_context_pending_graph_activations(&computed)!=2)fail("graph activation queue execution");
    TinyvmGraphActivationRecord first_reference={0},first_computed={0};if(!tinyvm_isa_v1_context_pop_graph_activation(&reference,&first_reference)||!tinyvm_isa_v1_context_pop_graph_activation(&computed,&first_computed)||first_reference.sequence!=0||first_computed.sequence!=0||first_reference.identity.activation_id!=10||first_computed.identity.activation_id!=10||tinyvm_isa_v1_context_pending_graph_activations(&reference)!=1||tinyvm_isa_v1_context_pending_graph_activations(&computed)!=1)fail("graph activation queue order");
    TinyvmGraphActivationRecord second_reference={0},second_computed={0};if(!tinyvm_isa_v1_context_pop_graph_activation(&reference,&second_reference)||!tinyvm_isa_v1_context_pop_graph_activation(&computed,&second_computed)||second_reference.sequence!=1||second_computed.sequence!=1||second_reference.identity.activation_id!=11||second_computed.identity.activation_id!=11||tinyvm_isa_v1_context_pending_graph_activations(&reference)||tinyvm_isa_v1_context_pending_graph_activations(&computed)||tinyvm_isa_v1_context_pop_graph_activation(&reference,&second_reference)||tinyvm_isa_v1_context_pop_graph_activation(&computed,&second_computed))fail("graph activation queue drain");
    tinyvm_isa_v1_context_destroy(&reference);tinyvm_isa_v1_context_destroy(&computed);
}
static void invalid_artifacts(void){
    char d[160];TinyvmConstant c[]={{1,TINYVM_CARRIER_I32,1}};InstrWord code[]={{TV1_CONST,0,2,0},{TV1_RETURN,0,0,0}};TinyvmProvenance p[2]={0};provenance(p,2);TinyvmArtifactV2 a=artifact(code,2,c,1,p,1);if(tinyvm_artifact_v2_validate(&a,d,sizeof d))fail("accepted missing constant");code[0]=(InstrWord){TV1_JMP,9,0,0};if(tinyvm_artifact_v2_validate(&a,d,sizeof d))fail("accepted invalid jump");code[0]=(InstrWord){TV1_CONST,0,1,0};code[1]=(InstrWord){TV1_NOP,0,0,0};if(tinyvm_artifact_v2_validate(&a,d,sizeof d))fail("accepted missing terminal");code[1]=(InstrWord){TV1_RETURN,0,0,0};id(p[1].source,"wrong-source");if(tinyvm_artifact_v2_validate(&a,d,sizeof d))fail("accepted provenance conflict");
}
int main(void){arithmetic_and_control();more_arithmetic();comparisons_and_terminals();handles();expected_traps();unresolved_import();resolved_import_engines();isa_v2_execution_inputs();graph_schedule_hook();graph_record_limit();graph_activation_queue();invalid_artifacts();puts("TinyVM typed ISA conformance passed");return 0;}
