#include <tinyvm/runtime_provider.h>

#include <dlfcn.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

typedef enum FlowTextOutcomeCode { FLOW_TEXT_SUCCESS = 0, FLOW_TEXT_INVALID_INPUT = 1, FLOW_TEXT_EXHAUSTED = 2, FLOW_TEXT_PROVIDER_UNAVAILABLE = 3 } FlowTextOutcomeCode;
typedef struct FlowTextOutcome { FlowTextOutcomeCode code; char *value; } FlowTextOutcome;
typedef struct TinyvmTextOutcome { int code; char *value; } TinyvmTextOutcome;
enum { TINYVM_TEXT_OUTCOME_TAG = 5, TINYVM_TEXT_VALUE_TAG = 6 };
#if defined(__clang__) || defined(__GNUC__)
#define TINYVM_NO_UBSAN __attribute__((no_sanitize("undefined")))
#else
#define TINYVM_NO_UBSAN
#endif
static const char *text_outcome_fault(int code) {
    if (code == 1) return "text outcome invalid_input";
    if (code == 2) return "text outcome exhausted";
    return "text outcome provider_unavailable";
}
static bool standard_type(const char *type){return !strcmp(type,"none")||!strcmp(type,"c_int")||!strcmp(type,"c_long")||!strcmp(type,"c_ulong")||!strcmp(type,"c_size_t")||!strcmp(type,"c_string")||!strcmp(type,"c_pointer")||!strcmp(type,"Text")||!strcmp(type,"TextOutcome");}
static bool aggregate_import(const TinyvmImport *x){if(!standard_type(x->result))return true;if(!strchr(x->parameters,',')&&!standard_type(x->parameters))return true;return false;}
/* The packed aggregate contract is a type-erased POSIX dlsym boundary.  The
 * lowerer admits only independently verified layouts that fit in one u64;
 * these helpers keep that deliberate ABI erasure isolated from UBSan's static
 * function-type instrumentation. */
static TINYVM_NO_UBSAN uint64_t aggregate_return_call(void *address){uint64_t (*function)(void)=NULL;*(void **)(&function)=address;return function();}
static TINYVM_NO_UBSAN uint64_t aggregate_stream_item_call(void *address,uint64_t index){uint64_t (*function)(size_t)=NULL;*(void **)(&function)=address;return function((size_t)index);}
static TINYVM_NO_UBSAN int aggregate_parameter_call(void *address,uint64_t value){int (*function)(uint64_t)=NULL;*(void **)(&function)=address;return function(value);}

static bool authorized(const char *path,const TinyvmImport *x){if(!path)return false;FILE *f=fopen(path,"r");if(!f)return false;char expected[512],legacy[512],line[512];snprintf(expected,sizeof expected,"allow %s %s %s %s %s %s",x->library,x->symbol,x->convention,x->effect,x->parameters,x->result);snprintf(legacy,sizeof legacy,"allow %s %s %s %s",x->library,x->symbol,x->convention,x->effect);bool found=false;while(fgets(line,sizeof line,f)){line[strcspn(line,"\r\n")]=0;if(strcmp(line,expected)==0||(!strcmp(x->parameters,"none")&&!strcmp(line,legacy))){found=true;break;}}fclose(f);return found;}
static const TinyvmString *string_by_id(const TinyvmArtifactV2 *a,uint64_t id){for(size_t i=0;i<a->string_count;++i)if(a->strings[i].id==id)return &a->strings[i];return NULL;}
static bool string_argument_allocation_failed(const TinyvmArtifactV2 *a,uint64_t handle,char *owned){const uint64_t tag=handle>>56,id=handle&UINT64_C(0x00ffffffffffffff);return tag==1&&string_by_id(a,id)!=NULL&&owned==NULL;}
static const char *runtime_string(const TinyvmRuntimeProvider *provider,uint64_t id){return id<provider->owned_string_count?provider->owned_strings[id].bytes:NULL;}
static const char *string_argument(const TinyvmArtifactV2 *a,const TinyvmRuntimeProvider *provider,uint64_t handle,char **owned){*owned=NULL;const uint64_t tag=handle>>56,id=handle&UINT64_C(0x00ffffffffffffff);if(tag==1){const TinyvmString *value=string_by_id(a,id);if(!value)return NULL;*owned=malloc(value->length+1);if(!*owned)return NULL;if(value->length&&!value->bytes){free(*owned);*owned=NULL;return NULL;}if(value->length)memcpy(*owned,value->bytes,value->length);(*owned)[value->length]=0;return *owned;}if(tag==3&&id<provider->argument_count)return provider->arguments[id];if(tag==4)return runtime_string(provider,id);if(tag==TINYVM_TEXT_VALUE_TAG&&id>0&&id<=provider->text_outcome_count)return ((TinyvmTextOutcome *)provider->text_outcomes)[id-1].value;return NULL;}
static TinyvmRuntimeStorage *storage_argument(TinyvmRuntimeProvider *provider,const TinyvmArtifactV2 *a,uint64_t handle,uint64_t count){const uint64_t tag=handle>>56,id=handle&UINT64_C(0x00ffffffffffffff);if(tag!=2||id==0||count>SIZE_MAX)return NULL;if(!provider->storage){provider->storage=calloc(a->storage_count,sizeof(*provider->storage));if(a->storage_count&&!provider->storage)return NULL;provider->storage_count=a->storage_count;for(size_t i=0;i<a->storage_count;++i){if(a->storage[i].id!=i+1||a->storage[i].bytes>SIZE_MAX)return NULL;provider->storage[i].length=(size_t)a->storage[i].bytes;provider->storage[i].bytes=calloc(provider->storage[i].length,1);provider->storage[i].initialized=calloc(provider->storage[i].length,1);if(!provider->storage[i].bytes||!provider->storage[i].initialized){free(provider->storage[i].bytes);free(provider->storage[i].initialized);provider->storage[i].bytes=NULL;provider->storage[i].initialized=NULL;return NULL;}}}if(id>provider->storage_count||count>provider->storage[id-1].length)return NULL;return &provider->storage[id-1];}
static bool storage_allocation_failed(const TinyvmRuntimeProvider *provider,const TinyvmArtifactV2 *a){if(!a->storage_count)return false;if(!provider->storage)return true;for(size_t i=0;i<provider->storage_count;++i)if(!provider->storage[i].bytes||!provider->storage[i].initialized)return true;return false;}
static bool storage_initialized(const TinyvmRuntimeStorage *storage,size_t count){for(size_t i=0;i<count;++i)if(!storage->initialized[i])return false;return true;}
static void storage_mark_initialized(TinyvmRuntimeStorage *storage,size_t count){memset(storage->initialized,1,count);}
static uint64_t own_runtime_string(TinyvmRuntimeProvider *provider,char *bytes,const char **fault){if(provider->owned_string_count==provider->owned_string_capacity){size_t capacity=provider->owned_string_capacity?provider->owned_string_capacity*2:8;TinyvmRuntimeString *items=realloc(provider->owned_strings,capacity*sizeof(*items));if(!items){free(bytes);*fault="runtime provider allocation exhausted";return 0;}provider->owned_strings=items;provider->owned_string_capacity=capacity;}const size_t id=provider->owned_string_count++;provider->owned_strings[id]=(TinyvmRuntimeString){bytes,strlen(bytes)};return UINT64_C(0x0400000000000000)|id;}
static bool track_file_descriptor(TinyvmRuntimeProvider *provider,int descriptor){if(provider->file_descriptor_count==provider->file_descriptor_capacity){size_t capacity=provider->file_descriptor_capacity?provider->file_descriptor_capacity*2:8;int *items=realloc(provider->file_descriptors,capacity*sizeof(*items));if(!items)return false;provider->file_descriptors=items;provider->file_descriptor_capacity=capacity;}provider->file_descriptors[provider->file_descriptor_count++]=descriptor;return true;}
static bool untrack_file_descriptor(TinyvmRuntimeProvider *provider,int descriptor){for(size_t i=0;i<provider->file_descriptor_count;++i)if(provider->file_descriptors[i]==descriptor){provider->file_descriptors[i]=provider->file_descriptors[--provider->file_descriptor_count];return true;}return false;}
static bool owns_file_descriptor(const TinyvmRuntimeProvider *provider,int descriptor){for(size_t i=0;i<provider->file_descriptor_count;++i)if(provider->file_descriptors[i]==descriptor)return true;return false;}
static uint64_t own_text_outcome(TinyvmRuntimeProvider *provider,FlowTextOutcome outcome,const char **fault){if(provider->text_outcome_count==provider->text_outcome_capacity){size_t capacity=provider->text_outcome_capacity?provider->text_outcome_capacity*2:8;TinyvmTextOutcome *items=realloc(provider->text_outcomes,capacity*sizeof(*items));if(!items){free(outcome.value);*fault="runtime provider allocation exhausted";return 0;}provider->text_outcomes=items;provider->text_outcome_capacity=capacity;}const size_t id=provider->text_outcome_count++;((TinyvmTextOutcome *)provider->text_outcomes)[id]=(TinyvmTextOutcome){outcome.code,outcome.value};return ((uint64_t)TINYVM_TEXT_OUTCOME_TAG<<56)|(id+1);}
void tinyvm_runtime_provider_destroy(TinyvmRuntimeProvider *provider){if(!provider)return;while(provider->file_descriptor_count){close(provider->file_descriptors[--provider->file_descriptor_count]);}free(provider->file_descriptors);provider->file_descriptors=NULL;provider->file_descriptor_capacity=0;for(size_t i=0;i<provider->owned_string_count;++i)free(provider->owned_strings[i].bytes);free(provider->owned_strings);provider->owned_strings=NULL;provider->owned_string_count=provider->owned_string_capacity=0;for(size_t i=0;i<provider->text_outcome_count;++i)free(((TinyvmTextOutcome *)provider->text_outcomes)[i].value);free(provider->text_outcomes);provider->text_outcomes=NULL;provider->text_outcome_count=provider->text_outcome_capacity=0;for(size_t i=0;i<provider->storage_count;++i){free(provider->storage[i].bytes);free(provider->storage[i].initialized);}free(provider->storage);provider->storage=NULL;provider->storage_count=0;}
bool tinyvm_runtime_provider_resolve_text_outcome(void *user,const TinyvmValue *value,bool value_field,TinyvmValue *result,const char **fault){TinyvmRuntimeProvider *provider=user;if(!provider||!value||value->carrier!=TINYVM_CARRIER_TEXT_OUTCOME){*fault="TextOutcome handle is invalid";return false;}const uint64_t tag=value->bits>>56,id=value->bits&UINT64_C(0x00ffffffffffffff);if(tag!=TINYVM_TEXT_OUTCOME_TAG||id==0||id>provider->text_outcome_count){*fault="TextOutcome handle is invalid";return false;}const TinyvmTextOutcome *outcome=&((TinyvmTextOutcome *)provider->text_outcomes)[id-1];if(value_field){if(outcome->code!=FLOW_TEXT_SUCCESS||!outcome->value){*fault="TextOutcome has no success value";return false;}*result=(TinyvmValue){TINYVM_CARRIER_OPAQUE_HANDLE,((uint64_t)TINYVM_TEXT_VALUE_TAG<<56)|id,true};}else *result=(TinyvmValue){TINYVM_CARRIER_I32,(uint64_t)(int64_t)outcome->code,true};return true;}
bool tinyvm_runtime_provider_preflight(const TinyvmRuntimeProvider *provider,const TinyvmArtifactV2 *artifact,const char **fault){if(!provider||!provider->policy_path){*fault="import artifact has no active policy";return false;}for(size_t i=0;i<artifact->import_count;++i)if(!authorized(provider->policy_path,&artifact->imports[i])){*fault="active policy does not authorize every exact import tuple";return false;}return true;}
bool tinyvm_runtime_provider_resolve(void *user,const TinyvmArtifactV2 *a,const TinyvmImport *x,const TinyvmValue *args,size_t count,TinyvmValue *out,const char **fault){
    TinyvmRuntimeProvider *provider=user;
    if(!provider||!authorized(provider->policy_path,x)){*fault="active policy does not authorize exact import tuple";return false;}
    if(strcmp(x->convention,"c") || ((strcmp(x->library,"libc.so.6") && strcmp(x->library,"libflowtext.so")) && strcmp(x->contract,"stream") && !(aggregate_import(x) || (!strcmp(x->effect,"readonly") && !strcmp(x->parameters,"none") && !strcmp(x->result,"c_size_t"))))){*fault="runtime provider does not admit import authority";return false;}
    void *library=dlopen(x->library,RTLD_NOW|RTLD_LOCAL);if(!library){*fault="authorized runtime library is unavailable";return false;}bool ok=false;bool exact_failure=false;
    if(!strcmp(x->contract,"libc")&&!strcmp(x->effect,"pure")&&!strcmp(x->symbol,"abs")&&!strcmp(x->parameters,"c_int")&&!strcmp(x->result,"c_int")&&count==1&&args[0].carrier==TINYVM_CARRIER_I32){int (*function)(int)=NULL;*(void **)(&function)=dlsym(library,"abs");if(function){const int value=function((int32_t)args[0].bits);*out=(TinyvmValue){TINYVM_CARRIER_I32,(uint64_t)(int64_t)value,true};ok=true;}}
    else if(!strcmp(x->contract,"libc")&&!strcmp(x->effect,"pure")&&!strcmp(x->symbol,"labs")&&!strcmp(x->parameters,"c_long")&&!strcmp(x->result,"c_long")&&count==1&&args[0].carrier==TINYVM_CARRIER_I64){long (*function)(long)=NULL;*(void **)(&function)=dlsym(library,"labs");if(function){*out=(TinyvmValue){TINYVM_CARRIER_I64,(uint64_t)(int64_t)function((long)(int64_t)args[0].bits),true};ok=true;}}
    else if(!strcmp(x->contract,"libc")&&!strcmp(x->effect,"pure")&&!strcmp(x->symbol,"strlen")&&!strcmp(x->parameters,"c_string")&&!strcmp(x->result,"c_size_t")&&count==1&&args[0].carrier==TINYVM_CARRIER_OPAQUE_HANDLE){size_t (*function)(const char *)=NULL;*(void **)(&function)=dlsym(library,"strlen");char *owned=NULL;const char *value=string_argument(a,provider,args[0].bits,&owned);if(function&&value){*out=(TinyvmValue){TINYVM_CARRIER_I64,function(value),true};ok=true;}else if(!value&&string_argument_allocation_failed(a,args[0].bits,owned))*fault="runtime provider allocation exhausted";free(owned);}
    else if(!strcmp(x->contract,"libc")&&!strcmp(x->effect,"pure")&&!strcmp(x->symbol,"strnlen")&&!strcmp(x->parameters,"c_string,c_size_t")&&!strcmp(x->result,"c_size_t")&&count==2&&args[0].carrier==TINYVM_CARRIER_OPAQUE_HANDLE&&args[1].carrier==TINYVM_CARRIER_I64){size_t (*function)(const char *,size_t)=NULL;*(void **)(&function)=dlsym(library,"strnlen");char *owned=NULL;const char *value=string_argument(a,provider,args[0].bits,&owned);if(function&&value){*out=(TinyvmValue){TINYVM_CARRIER_I64,function(value,(size_t)args[1].bits),true};ok=true;}else if(!value&&string_argument_allocation_failed(a,args[0].bits,owned))*fault="runtime provider allocation exhausted";free(owned);}
    else if(!strcmp(x->contract,"ctype")&&!strcmp(x->effect,"pure")&&(!strcmp(x->symbol,"tolower")||!strcmp(x->symbol,"toupper"))&&!strcmp(x->parameters,"c_int")&&!strcmp(x->result,"c_int")&&count==1&&args[0].carrier==TINYVM_CARRIER_I32){int (*function)(int)=NULL;*(void **)(&function)=dlsym(library,x->symbol);if(function){*out=(TinyvmValue){TINYVM_CARRIER_I32,(uint64_t)(int64_t)function((int32_t)args[0].bits),true};ok=true;}}
    else if(!strcmp(x->contract,"file_io")&&!strcmp(x->effect,"io")&&!strcmp(x->symbol,"open")&&!strcmp(x->parameters,"c_string,c_int")&&!strcmp(x->result,"c_int")&&count==2&&args[0].carrier==TINYVM_CARRIER_OPAQUE_HANDLE&&args[1].carrier==TINYVM_CARRIER_I32){int (*function)(const char *,int)=NULL;*(void **)(&function)=dlsym(library,"open");char *owned=NULL;const char *path=string_argument(a,provider,args[0].bits,&owned);if(function&&path){const int descriptor=function(path,(int32_t)args[1].bits);if(descriptor>=0){if(!track_file_descriptor(provider,descriptor)){close(descriptor);*fault="runtime provider allocation exhausted";exact_failure=true;}else{*out=(TinyvmValue){TINYVM_CARRIER_I32,(uint64_t)(int64_t)descriptor,true};ok=true;}}else{*out=(TinyvmValue){TINYVM_CARRIER_I32,(uint64_t)(int64_t)descriptor,true};ok=true;}}else if(!path&&string_argument_allocation_failed(a,args[0].bits,owned))*fault="runtime provider allocation exhausted";free(owned);}
    else if(!strcmp(x->contract,"file_io")&&!strcmp(x->effect,"io")&&!strcmp(x->symbol,"close")&&!strcmp(x->parameters,"c_int")&&!strcmp(x->result,"c_int")&&count==1&&args[0].carrier==TINYVM_CARRIER_I32){int (*function)(int)=NULL;*(void **)(&function)=dlsym(library,"close");const int descriptor=(int32_t)args[0].bits;if(!untrack_file_descriptor(provider,descriptor)){*fault="file descriptor is not owned by the runtime";exact_failure=true;}else if(function){*out=(TinyvmValue){TINYVM_CARRIER_I32,(uint64_t)(int64_t)function(descriptor),true};ok=true;}}
    else if(!strcmp(x->contract,"file_io")&&!strcmp(x->effect,"io")&&!strcmp(x->symbol,"read")&&!strcmp(x->parameters,"c_int,c_pointer,c_size_t")&&!strcmp(x->result,"c_long")&&count==3&&args[0].carrier==TINYVM_CARRIER_I32&&args[1].carrier==TINYVM_CARRIER_OPAQUE_HANDLE&&args[2].carrier==TINYVM_CARRIER_I64){ssize_t (*function)(int,void *,size_t)=NULL;*(void **)(&function)=dlsym(library,"read");const int descriptor=(int32_t)args[0].bits;const size_t length=(size_t)args[2].bits;TinyvmRuntimeStorage *storage=storage_argument(provider,a,args[1].bits,args[2].bits);if(!storage||!owns_file_descriptor(provider,descriptor)){if(!storage)*fault="file I/O storage bounds violation";else *fault="file descriptor is not owned by the runtime";exact_failure=true;}else if(function){const ssize_t transferred=function(descriptor,storage->bytes,length);if(transferred>0)storage_mark_initialized(storage,(size_t)transferred);*out=(TinyvmValue){TINYVM_CARRIER_I64,(uint64_t)(int64_t)transferred,true};ok=true;}}
    else if(!strcmp(x->contract,"file_io")&&!strcmp(x->effect,"io")&&!strcmp(x->symbol,"write")&&!strcmp(x->parameters,"c_int,c_pointer,c_size_t")&&!strcmp(x->result,"c_long")&&count==3&&args[0].carrier==TINYVM_CARRIER_I32&&args[1].carrier==TINYVM_CARRIER_OPAQUE_HANDLE&&args[2].carrier==TINYVM_CARRIER_I64){ssize_t (*function)(int,const void *,size_t)=NULL;*(void **)(&function)=dlsym(library,"write");const int descriptor=(int32_t)args[0].bits;const size_t length=(size_t)args[2].bits;TinyvmRuntimeStorage *storage=storage_argument(provider,a,args[1].bits,args[2].bits);if(!storage||!owns_file_descriptor(provider,descriptor)){if(!storage)*fault="file I/O storage bounds violation";else *fault="file descriptor is not owned by the runtime";exact_failure=true;}else if(!storage_initialized(storage,length)){*fault="file I/O read from uninitialized storage";exact_failure=true;}else if(function){const ssize_t transferred=function(descriptor,storage->bytes,length);*out=(TinyvmValue){TINYVM_CARRIER_I64,(uint64_t)(int64_t)transferred,true};ok=true;}}
    else if(!strcmp(x->contract,"libc")&&!strcmp(x->effect,"io")&&!strcmp(x->symbol,"puts")&&(!strcmp(x->parameters,"c_string")||!strcmp(x->parameters,"Text"))&&!strcmp(x->result,"c_int")&&count==1&&args[0].carrier==TINYVM_CARRIER_OPAQUE_HANDLE){int (*function)(const char *)=NULL;*(void **)(&function)=dlsym(library,"puts");char *owned=NULL;const char *value=string_argument(a,provider,args[0].bits,&owned);if(function&&value){*out=(TinyvmValue){TINYVM_CARRIER_I32,(uint64_t)(int64_t)function(value),true};ok=true;}else if(!value&&string_argument_allocation_failed(a,args[0].bits,owned))*fault="runtime provider allocation exhausted";free(owned);}
    else if(!strcmp(x->contract,"text_runtime")&&!strcmp(x->effect,"memory")&&!strcmp(x->symbol,"flow_text_concat_value")&&!strcmp(x->parameters,"Text,Text")&&!strcmp(x->result,"TextOutcome")&&count==2&&args[0].carrier==TINYVM_CARRIER_OPAQUE_HANDLE&&args[1].carrier==TINYVM_CARRIER_OPAQUE_HANDLE){FlowTextOutcome (*function)(const char *,const char *)=NULL;*(void **)(&function)=dlsym(library,"flow_text_concat_value");char *left_owned=NULL,*right_owned=NULL;const char *left=string_argument(a,provider,args[0].bits,&left_owned),*right=string_argument(a,provider,args[1].bits,&right_owned);const bool allocation_failure=(!left&&string_argument_allocation_failed(a,args[0].bits,left_owned))||(!right&&string_argument_allocation_failed(a,args[1].bits,right_owned));FlowTextOutcome outcome={FLOW_TEXT_PROVIDER_UNAVAILABLE,NULL};if(allocation_failure){*fault="runtime provider allocation exhausted";exact_failure=true;}else if(function&&left&&right)outcome=function(left,right);else if(!left||!right)outcome.code=FLOW_TEXT_INVALID_INPUT;if(!exact_failure){const uint64_t handle=own_text_outcome(provider,outcome,fault);if(handle){*out=(TinyvmValue){TINYVM_CARRIER_TEXT_OUTCOME,handle,true};ok=true;}}free(left_owned);free(right_owned);}
    else if(!strcmp(x->contract,"text_runtime")&&!strcmp(x->effect,"memory")&&!strcmp(x->symbol,"flow_text_concat")&&!strcmp(x->parameters,"Text,Text")&&!strcmp(x->result,"Text")&&count==2&&args[0].carrier==TINYVM_CARRIER_OPAQUE_HANDLE&&args[1].carrier==TINYVM_CARRIER_OPAQUE_HANDLE){FlowTextOutcomeCode (*function)(const char *,const char *,FlowTextOutcome *)=NULL;*(void **)(&function)=dlsym(library,"flow_text_concat_outcome");char *left_owned=NULL,*right_owned=NULL;const char *left=string_argument(a,provider,args[0].bits,&left_owned),*right=string_argument(a,provider,args[1].bits,&right_owned);const bool allocation_failure=(!left&&string_argument_allocation_failed(a,args[0].bits,left_owned))||(!right&&string_argument_allocation_failed(a,args[1].bits,right_owned));FlowTextOutcome outcome={FLOW_TEXT_PROVIDER_UNAVAILABLE,NULL};if(allocation_failure){*fault="runtime provider allocation exhausted";exact_failure=true;}else{if(function&&left&&right)function(left,right,&outcome);if(outcome.code!=0){*fault=text_outcome_fault(outcome.code);exact_failure=true;}else if(outcome.value){const uint64_t handle=own_runtime_string(provider,outcome.value,fault);if(handle){*out=(TinyvmValue){TINYVM_CARRIER_OPAQUE_HANDLE,handle,true};outcome.value=NULL;ok=true;}}}free(outcome.value);free(left_owned);free(right_owned);}
    else if(!strcmp(x->contract,"text_runtime")&&!strcmp(x->effect,"memory")&&!strcmp(x->symbol,"flow_text_concat_status")&&!strcmp(x->parameters,"Text,Text")&&!strcmp(x->result,"c_int")&&count==2&&args[0].carrier==TINYVM_CARRIER_OPAQUE_HANDLE&&args[1].carrier==TINYVM_CARRIER_OPAQUE_HANDLE){FlowTextOutcomeCode (*function)(const char *,const char *)=NULL;*(void **)(&function)=dlsym(library,"flow_text_concat_status");char *left_owned=NULL,*right_owned=NULL;const char *left=string_argument(a,provider,args[0].bits,&left_owned),*right=string_argument(a,provider,args[1].bits,&right_owned);const bool allocation_failure=(!left&&string_argument_allocation_failed(a,args[0].bits,left_owned))||(!right&&string_argument_allocation_failed(a,args[1].bits,right_owned));if(allocation_failure){*fault="runtime provider allocation exhausted";exact_failure=true;}else if(function&&left&&right){*out=(TinyvmValue){TINYVM_CARRIER_I32,(uint64_t)(int64_t)function(left,right),true};ok=true;}else if(!left||!right){*out=(TinyvmValue){TINYVM_CARRIER_I32,FLOW_TEXT_INVALID_INPUT,true};ok=true;}free(left_owned);free(right_owned);}
    else if(!strcmp(x->contract,"text_runtime")&&!strcmp(x->effect,"memory")&&!strcmp(x->symbol,"flow_text_dispose")&&!strcmp(x->parameters,"Text")&&!strcmp(x->result,"c_int")&&count==1&&args[0].carrier==TINYVM_CARRIER_OPAQUE_HANDLE){const uint64_t tag=args[0].bits>>56,id=args[0].bits&UINT64_C(0x00ffffffffffffff);if(tag==TINYVM_TEXT_VALUE_TAG&&id>0&&id<=provider->text_outcome_count){TinyvmTextOutcome *outcome=&((TinyvmTextOutcome *)provider->text_outcomes)[id-1];free(outcome->value);outcome->value=NULL;*out=(TinyvmValue){TINYVM_CARRIER_I32,0,true};ok=true;}else if(tag==4&&id<provider->owned_string_count){free(provider->owned_strings[id].bytes);provider->owned_strings[id].bytes=NULL;*out=(TinyvmValue){TINYVM_CARRIER_I32,0,true};ok=true;}}
    else if((!strcmp(x->contract,"memory")||!strcmp(x->contract,"libc"))&&!strcmp(x->effect,"io")&&!strcmp(x->symbol,"memset")&&!strcmp(x->parameters,"c_pointer,c_int,c_size_t")&&!strcmp(x->result,"c_pointer")&&count==3&&args[0].carrier==TINYVM_CARRIER_OPAQUE_HANDLE&&args[1].carrier==TINYVM_CARRIER_I32&&args[2].carrier==TINYVM_CARRIER_I64){void *(*function)(void *,int,size_t)=NULL;*(void **)(&function)=dlsym(library,"memset");TinyvmRuntimeStorage *destination=storage_argument(provider,a,args[0].bits,args[2].bits);if(!destination){if(storage_allocation_failed(provider,a))*fault="runtime provider allocation exhausted";else *fault="memory storage bounds violation";exact_failure=true;}else if(function){function(destination->bytes,(int32_t)args[1].bits,(size_t)args[2].bits);*out=(TinyvmValue){TINYVM_CARRIER_OPAQUE_HANDLE,args[0].bits,true};ok=true;}}
    else if((!strcmp(x->contract,"memory")||!strcmp(x->contract,"libc"))&&!strcmp(x->effect,"io")&&!strcmp(x->symbol,"memcpy")&&!strcmp(x->parameters,"c_pointer,c_pointer,c_size_t")&&!strcmp(x->result,"c_pointer")&&count==3&&args[0].carrier==TINYVM_CARRIER_OPAQUE_HANDLE&&args[1].carrier==TINYVM_CARRIER_OPAQUE_HANDLE&&args[2].carrier==TINYVM_CARRIER_I64){void *(*function)(void *,const void *,size_t)=NULL;*(void **)(&function)=dlsym(library,"memcpy");TinyvmRuntimeStorage *destination=storage_argument(provider,a,args[0].bits,args[2].bits),*source=storage_argument(provider,a,args[1].bits,args[2].bits);if(!destination||!source){*fault="memory storage bounds violation";exact_failure=true;}else if(function){function(destination->bytes,source->bytes,(size_t)args[2].bits);*out=(TinyvmValue){TINYVM_CARRIER_OPAQUE_HANDLE,args[0].bits,true};ok=true;}}
    else if((!strcmp(x->contract,"memory")||!strcmp(x->contract,"libc"))&&!strcmp(x->effect,"io")&&!strcmp(x->symbol,"memmove")&&!strcmp(x->parameters,"c_pointer,c_pointer,c_size_t")&&!strcmp(x->result,"c_pointer")&&count==3&&args[0].carrier==TINYVM_CARRIER_OPAQUE_HANDLE&&args[1].carrier==TINYVM_CARRIER_OPAQUE_HANDLE&&args[2].carrier==TINYVM_CARRIER_I64){void *(*function)(void *,const void *,size_t)=NULL;*(void **)(&function)=dlsym(library,"memmove");TinyvmRuntimeStorage *destination=storage_argument(provider,a,args[0].bits,args[2].bits),*source=storage_argument(provider,a,args[1].bits,args[2].bits);if(!destination||!source){*fault="memory storage bounds violation";exact_failure=true;}else if(function){function(destination->bytes,source->bytes,(size_t)args[2].bits);*out=(TinyvmValue){TINYVM_CARRIER_OPAQUE_HANDLE,args[0].bits,true};ok=true;}}
    else if((!strcmp(x->contract,"memory")||!strcmp(x->contract,"libc"))&&!strcmp(x->effect,"pure")&&!strcmp(x->symbol,"memcmp")&&!strcmp(x->parameters,"c_pointer,c_pointer,c_size_t")&&!strcmp(x->result,"c_int")&&count==3&&args[0].carrier==TINYVM_CARRIER_OPAQUE_HANDLE&&args[1].carrier==TINYVM_CARRIER_OPAQUE_HANDLE&&args[2].carrier==TINYVM_CARRIER_I64){int (*function)(const void *,const void *,size_t)=NULL;*(void **)(&function)=dlsym(library,"memcmp");TinyvmRuntimeStorage *left=storage_argument(provider,a,args[0].bits,args[2].bits),*right=storage_argument(provider,a,args[1].bits,args[2].bits);if(!left||!right){*fault="memory storage bounds violation";exact_failure=true;}else if(function){*out=(TinyvmValue){TINYVM_CARRIER_I32,(uint64_t)(int64_t)function(left->bytes,right->bytes,(size_t)args[2].bits),true};ok=true;}}
    else if((!strcmp(x->contract,"kernel")||!strcmp(x->contract,"linux"))&&!strcmp(x->effect,"readonly")&&!strcmp(x->parameters,"none")&&!strcmp(x->result,"c_int")&&count==0&&(!strcmp(x->symbol,"getpid")||!strcmp(x->symbol,"getuid")||!strcmp(x->symbol,"getgid")||!strcmp(x->symbol,"geteuid")||!strcmp(x->symbol,"getegid")||!strcmp(x->symbol,"getppid")||!strcmp(x->symbol,"getpgrp"))){int (*function)(void)=NULL;*(void **)(&function)=dlsym(library,x->symbol);if(function){*out=(TinyvmValue){TINYVM_CARRIER_I32,(uint64_t)(int64_t)function(),true};ok=true;}}
    else if((!strcmp(x->contract,"kernel")||!strcmp(x->contract,"linux"))&&!strcmp(x->effect,"readonly")&&!strcmp(x->parameters,"c_int")&&!strcmp(x->result,"c_int")&&count==1&&args[0].carrier==TINYVM_CARRIER_I32&&(!strcmp(x->symbol,"getpgid")||!strcmp(x->symbol,"getsid"))){int (*function)(int)=NULL;*(void **)(&function)=dlsym(library,x->symbol);if(function){*out=(TinyvmValue){TINYVM_CARRIER_I32,(uint64_t)(int64_t)function((int32_t)args[0].bits),true};ok=true;}}
    else if((!strcmp(x->contract,"kernel")||!strcmp(x->contract,"linux"))&&!strcmp(x->effect,"readonly")&&!strcmp(x->symbol,"getpriority")&&!strcmp(x->parameters,"c_int,c_int")&&!strcmp(x->result,"c_int")&&count==2&&args[0].carrier==TINYVM_CARRIER_I32&&args[1].carrier==TINYVM_CARRIER_I32){int (*function)(int,int)=NULL;*(void **)(&function)=dlsym(library,"getpriority");if(function){*out=(TinyvmValue){TINYVM_CARRIER_I32,(uint64_t)(int64_t)function((int32_t)args[0].bits,(int32_t)args[1].bits),true};ok=true;}}
    else if(!strcmp(x->effect,"readonly")&&!strcmp(x->parameters,"none")&&!strcmp(x->result,"c_size_t")&&count==0){size_t (*function)(void)=NULL;*(void **)(&function)=dlsym(library,x->symbol);if(function){*out=(TinyvmValue){TINYVM_CARRIER_I64,(uint64_t)function(),true};ok=true;}}
    else if(!strcmp(x->contract,"stream")&&!strcmp(x->effect,"readonly")&&!strcmp(x->parameters,"c_size_t")&&!strcmp(x->result,"c_int")&&count==1&&args[0].carrier==TINYVM_CARRIER_I64){int (*function)(size_t)=NULL;*(void **)(&function)=dlsym(library,x->symbol);if(function){*out=(TinyvmValue){TINYVM_CARRIER_I32,(uint64_t)(int64_t)function((size_t)args[0].bits),true};ok=true;}}
    else if(!strcmp(x->effect,"readonly")&&!strcmp(x->parameters,"c_size_t")&&aggregate_import(x)&&count==1&&args[0].carrier==TINYVM_CARRIER_I64){void *function=dlsym(library,x->symbol);if(function){*out=(TinyvmValue){TINYVM_CARRIER_I64,aggregate_stream_item_call(function,args[0].bits),true};ok=true;}}
    else if(aggregate_import(x)&&!strcmp(x->parameters,"none")&&count==0){void *function=dlsym(library,x->symbol);if(function){*out=(TinyvmValue){TINYVM_CARRIER_I64,aggregate_return_call(function),true};ok=true;}}
    else if(aggregate_import(x)&&count==1&&args[0].carrier==TINYVM_CARRIER_I64&&!strcmp(x->result,"c_int")){void *function=dlsym(library,x->symbol);if(function){*out=(TinyvmValue){TINYVM_CARRIER_I32,(uint64_t)(int64_t)aggregate_parameter_call(function,args[0].bits),true};ok=true;}}
    if(!ok&&!exact_failure&&(!fault||!*fault))*fault="no exact typed runtime thunk for import";
    dlclose(library);
    return ok;
}
