#include <tinyvm/runtime_provider.h>

#include <dlfcn.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct FlowTextOutcome { int code; char *value; } FlowTextOutcome;
enum { FLOW_TEXT_SUCCESS = 0, FLOW_TEXT_INVALID_INPUT = 1, FLOW_TEXT_EXHAUSTED = 2, FLOW_TEXT_PROVIDER_UNAVAILABLE = 3 };
static const char *text_outcome_fault(int code) {
    if (code == 1) return "text outcome invalid_input";
    if (code == 2) return "text outcome exhausted";
    return "text outcome provider_unavailable";
}

static bool authorized(const char *path,const TinyvmImport *x){if(!path)return false;FILE *f=fopen(path,"r");if(!f)return false;char expected[512],legacy[512],line[512];snprintf(expected,sizeof expected,"allow %s %s %s %s %s %s",x->library,x->symbol,x->convention,x->effect,x->parameters,x->result);snprintf(legacy,sizeof legacy,"allow %s %s %s %s",x->library,x->symbol,x->convention,x->effect);bool found=false;while(fgets(line,sizeof line,f)){line[strcspn(line,"\r\n")]=0;if(strcmp(line,expected)==0||(!strcmp(x->parameters,"none")&&!strcmp(line,legacy))){found=true;break;}}fclose(f);return found;}
static const TinyvmString *string_by_id(const TinyvmArtifactV2 *a,uint64_t id){for(size_t i=0;i<a->string_count;++i)if(a->strings[i].id==id)return &a->strings[i];return NULL;}
static const char *runtime_string(const TinyvmRuntimeProvider *provider,uint64_t id){return id<provider->owned_string_count?provider->owned_strings[id].bytes:NULL;}
static const char *string_argument(const TinyvmArtifactV2 *a,const TinyvmRuntimeProvider *provider,uint64_t handle,char **owned){*owned=NULL;const uint64_t tag=handle>>56,id=handle&UINT64_C(0x00ffffffffffffff);if(tag==1){const TinyvmString *value=string_by_id(a,id);if(!value)return NULL;*owned=malloc(value->length+1);if(!*owned)return NULL;memcpy(*owned,value->bytes,value->length);(*owned)[value->length]=0;return *owned;}if(tag==3&&id<provider->argument_count)return provider->arguments[id];if(tag==4)return runtime_string(provider,id);return NULL;}
static TinyvmRuntimeStorage *storage_argument(TinyvmRuntimeProvider *provider,const TinyvmArtifactV2 *a,uint64_t handle,uint64_t count){const uint64_t tag=handle>>56,id=handle&UINT64_C(0x00ffffffffffffff);if(tag!=2||id==0||count>SIZE_MAX)return NULL;if(!provider->storage){provider->storage=calloc(a->storage_count,sizeof(*provider->storage));if(a->storage_count&&!provider->storage)return NULL;provider->storage_count=a->storage_count;for(size_t i=0;i<a->storage_count;++i){if(a->storage[i].id!=i+1||a->storage[i].bytes>SIZE_MAX)return NULL;provider->storage[i].length=(size_t)a->storage[i].bytes;provider->storage[i].bytes=calloc(provider->storage[i].length,1);if(!provider->storage[i].bytes)return NULL;}}if(id>provider->storage_count||count>provider->storage[id-1].length)return NULL;return &provider->storage[id-1];}
static uint64_t own_runtime_string(TinyvmRuntimeProvider *provider,char *bytes){if(provider->owned_string_count==provider->owned_string_capacity){size_t capacity=provider->owned_string_capacity?provider->owned_string_capacity*2:8;TinyvmRuntimeString *items=realloc(provider->owned_strings,capacity*sizeof(*items));if(!items){free(bytes);return 0;}provider->owned_strings=items;provider->owned_string_capacity=capacity;}const size_t id=provider->owned_string_count++;provider->owned_strings[id]=(TinyvmRuntimeString){bytes,strlen(bytes)};return UINT64_C(0x0400000000000000)|id;}
void tinyvm_runtime_provider_destroy(TinyvmRuntimeProvider *provider){if(!provider)return;for(size_t i=0;i<provider->owned_string_count;++i)free(provider->owned_strings[i].bytes);free(provider->owned_strings);provider->owned_strings=NULL;provider->owned_string_count=provider->owned_string_capacity=0;for(size_t i=0;i<provider->storage_count;++i)free(provider->storage[i].bytes);free(provider->storage);provider->storage=NULL;provider->storage_count=0;}
bool tinyvm_runtime_provider_preflight(const TinyvmRuntimeProvider *provider,const TinyvmArtifactV2 *artifact,const char **fault){if(!provider||!provider->policy_path){*fault="import artifact has no active policy";return false;}for(size_t i=0;i<artifact->import_count;++i)if(!authorized(provider->policy_path,&artifact->imports[i])){*fault="active policy does not authorize every exact import tuple";return false;}return true;}
bool tinyvm_runtime_provider_resolve(void *user,const TinyvmArtifactV2 *a,const TinyvmImport *x,const TinyvmValue *args,size_t count,TinyvmValue *out,const char **fault){
    TinyvmRuntimeProvider *provider=user;
    if(!provider||!authorized(provider->policy_path,x)){*fault="active policy does not authorize exact import tuple";return false;}
    if(strcmp(x->convention,"c") || (strcmp(x->library,"libc.so.6") && strcmp(x->library,"libflowtext.so"))){*fault="runtime provider does not admit import authority";return false;}
    void *library=dlopen(x->library,RTLD_NOW|RTLD_LOCAL);if(!library){*fault="authorized runtime library is unavailable";return false;}bool ok=false;bool exact_failure=false;
    if(!strcmp(x->contract,"libc")&&!strcmp(x->effect,"pure")&&!strcmp(x->symbol,"abs")&&!strcmp(x->parameters,"c_int")&&!strcmp(x->result,"c_int")&&count==1&&args[0].carrier==TINYVM_CARRIER_I32){int (*function)(int)=NULL;*(void **)(&function)=dlsym(library,"abs");if(function){const int value=function((int32_t)args[0].bits);*out=(TinyvmValue){TINYVM_CARRIER_I32,(uint64_t)(int64_t)value,true};ok=true;}}
    else if(!strcmp(x->contract,"libc")&&!strcmp(x->effect,"pure")&&!strcmp(x->symbol,"labs")&&!strcmp(x->parameters,"c_long")&&!strcmp(x->result,"c_long")&&count==1&&args[0].carrier==TINYVM_CARRIER_I64){long (*function)(long)=NULL;*(void **)(&function)=dlsym(library,"labs");if(function){*out=(TinyvmValue){TINYVM_CARRIER_I64,(uint64_t)(int64_t)function((long)(int64_t)args[0].bits),true};ok=true;}}
    else if(!strcmp(x->contract,"libc")&&!strcmp(x->effect,"pure")&&!strcmp(x->symbol,"strlen")&&!strcmp(x->parameters,"c_string")&&!strcmp(x->result,"c_size_t")&&count==1&&args[0].carrier==TINYVM_CARRIER_OPAQUE_HANDLE){size_t (*function)(const char *)=NULL;*(void **)(&function)=dlsym(library,"strlen");char *owned=NULL;const char *value=string_argument(a,provider,args[0].bits,&owned);if(function&&value){*out=(TinyvmValue){TINYVM_CARRIER_I64,function(value),true};ok=true;}free(owned);}
    else if(!strcmp(x->contract,"libc")&&!strcmp(x->effect,"io")&&!strcmp(x->symbol,"puts")&&(!strcmp(x->parameters,"c_string")||!strcmp(x->parameters,"Text"))&&!strcmp(x->result,"c_int")&&count==1&&args[0].carrier==TINYVM_CARRIER_OPAQUE_HANDLE){int (*function)(const char *)=NULL;*(void **)(&function)=dlsym(library,"puts");char *owned=NULL;const char *value=string_argument(a,provider,args[0].bits,&owned);if(function&&value){*out=(TinyvmValue){TINYVM_CARRIER_I32,(uint64_t)(int64_t)function(value),true};ok=true;}free(owned);}
    else if(!strcmp(x->contract,"text_runtime")&&!strcmp(x->effect,"memory")&&!strcmp(x->symbol,"flow_text_concat")&&!strcmp(x->parameters,"Text,Text")&&!strcmp(x->result,"Text")&&count==2&&args[0].carrier==TINYVM_CARRIER_OPAQUE_HANDLE&&args[1].carrier==TINYVM_CARRIER_OPAQUE_HANDLE){int (*function)(const char *,const char *,FlowTextOutcome *)=NULL;*(void **)(&function)=dlsym(library,"flow_text_concat_outcome");char *left_owned=NULL,*right_owned=NULL;const char *left=string_argument(a,provider,args[0].bits,&left_owned),*right=string_argument(a,provider,args[1].bits,&right_owned);FlowTextOutcome outcome={3,NULL};if(function&&left&&right)function(left,right,&outcome);if(outcome.code!=0){*fault=text_outcome_fault(outcome.code);exact_failure=true;}else if(outcome.value){const uint64_t handle=own_runtime_string(provider,outcome.value);if(handle){*out=(TinyvmValue){TINYVM_CARRIER_OPAQUE_HANDLE,handle,true};outcome.value=NULL;ok=true;}}free(outcome.value);free(left_owned);free(right_owned);}
    else if(!strcmp(x->contract,"text_runtime")&&!strcmp(x->effect,"memory")&&!strcmp(x->symbol,"flow_text_concat_status")&&!strcmp(x->parameters,"Text,Text")&&!strcmp(x->result,"c_int")&&count==2&&args[0].carrier==TINYVM_CARRIER_OPAQUE_HANDLE&&args[1].carrier==TINYVM_CARRIER_OPAQUE_HANDLE){int (*function)(const char *,const char *)=NULL;*(void **)(&function)=dlsym(library,"flow_text_concat_status");char *left_owned=NULL,*right_owned=NULL;const char *left=string_argument(a,provider,args[0].bits,&left_owned),*right=string_argument(a,provider,args[1].bits,&right_owned);if(function&&left&&right){*out=(TinyvmValue){TINYVM_CARRIER_I32,(uint64_t)(int64_t)function(left,right),true};ok=true;}else if(!left||!right){*out=(TinyvmValue){TINYVM_CARRIER_I32,FLOW_TEXT_INVALID_INPUT,true};ok=true;}free(left_owned);free(right_owned);}
    else if((!strcmp(x->contract,"memory")||!strcmp(x->contract,"libc"))&&!strcmp(x->effect,"io")&&!strcmp(x->symbol,"memset")&&!strcmp(x->parameters,"c_pointer,c_int,c_size_t")&&!strcmp(x->result,"c_pointer")&&count==3&&args[0].carrier==TINYVM_CARRIER_OPAQUE_HANDLE&&args[1].carrier==TINYVM_CARRIER_I32&&args[2].carrier==TINYVM_CARRIER_I64){void *(*function)(void *,int,size_t)=NULL;*(void **)(&function)=dlsym(library,"memset");TinyvmRuntimeStorage *destination=storage_argument(provider,a,args[0].bits,args[2].bits);if(!destination){*fault="memory storage bounds violation";exact_failure=true;}else if(function){function(destination->bytes,(int32_t)args[1].bits,(size_t)args[2].bits);*out=(TinyvmValue){TINYVM_CARRIER_OPAQUE_HANDLE,args[0].bits,true};ok=true;}}
    else if((!strcmp(x->contract,"memory")||!strcmp(x->contract,"libc"))&&!strcmp(x->effect,"io")&&!strcmp(x->symbol,"memcpy")&&!strcmp(x->parameters,"c_pointer,c_pointer,c_size_t")&&!strcmp(x->result,"c_pointer")&&count==3&&args[0].carrier==TINYVM_CARRIER_OPAQUE_HANDLE&&args[1].carrier==TINYVM_CARRIER_OPAQUE_HANDLE&&args[2].carrier==TINYVM_CARRIER_I64){void *(*function)(void *,const void *,size_t)=NULL;*(void **)(&function)=dlsym(library,"memcpy");TinyvmRuntimeStorage *destination=storage_argument(provider,a,args[0].bits,args[2].bits),*source=storage_argument(provider,a,args[1].bits,args[2].bits);if(!destination||!source){*fault="memory storage bounds violation";exact_failure=true;}else if(function){function(destination->bytes,source->bytes,(size_t)args[2].bits);*out=(TinyvmValue){TINYVM_CARRIER_OPAQUE_HANDLE,args[0].bits,true};ok=true;}}
    else if((!strcmp(x->contract,"memory")||!strcmp(x->contract,"libc"))&&!strcmp(x->effect,"pure")&&!strcmp(x->symbol,"memcmp")&&!strcmp(x->parameters,"c_pointer,c_pointer,c_size_t")&&!strcmp(x->result,"c_int")&&count==3&&args[0].carrier==TINYVM_CARRIER_OPAQUE_HANDLE&&args[1].carrier==TINYVM_CARRIER_OPAQUE_HANDLE&&args[2].carrier==TINYVM_CARRIER_I64){int (*function)(const void *,const void *,size_t)=NULL;*(void **)(&function)=dlsym(library,"memcmp");TinyvmRuntimeStorage *left=storage_argument(provider,a,args[0].bits,args[2].bits),*right=storage_argument(provider,a,args[1].bits,args[2].bits);if(!left||!right){*fault="memory storage bounds violation";exact_failure=true;}else if(function){*out=(TinyvmValue){TINYVM_CARRIER_I32,(uint64_t)(int64_t)function(left->bytes,right->bytes,(size_t)args[2].bits),true};ok=true;}}
    else if((!strcmp(x->contract,"kernel")||!strcmp(x->contract,"linux"))&&!strcmp(x->effect,"readonly")&&!strcmp(x->parameters,"none")&&!strcmp(x->result,"c_int")&&count==0&&(!strcmp(x->symbol,"getpid")||!strcmp(x->symbol,"getuid")||!strcmp(x->symbol,"getgid")||!strcmp(x->symbol,"geteuid")||!strcmp(x->symbol,"getegid")||!strcmp(x->symbol,"getppid")||!strcmp(x->symbol,"getpgrp"))){int (*function)(void)=NULL;*(void **)(&function)=dlsym(library,x->symbol);if(function){*out=(TinyvmValue){TINYVM_CARRIER_I32,(uint64_t)(int64_t)function(),true};ok=true;}}
    else if((!strcmp(x->contract,"kernel")||!strcmp(x->contract,"linux"))&&!strcmp(x->effect,"readonly")&&!strcmp(x->parameters,"c_int")&&!strcmp(x->result,"c_int")&&count==1&&args[0].carrier==TINYVM_CARRIER_I32&&(!strcmp(x->symbol,"getpgid")||!strcmp(x->symbol,"getsid"))){int (*function)(int)=NULL;*(void **)(&function)=dlsym(library,x->symbol);if(function){*out=(TinyvmValue){TINYVM_CARRIER_I32,(uint64_t)(int64_t)function((int32_t)args[0].bits),true};ok=true;}}
    else if((!strcmp(x->contract,"kernel")||!strcmp(x->contract,"linux"))&&!strcmp(x->effect,"readonly")&&!strcmp(x->symbol,"getpriority")&&!strcmp(x->parameters,"c_int,c_int")&&!strcmp(x->result,"c_int")&&count==2&&args[0].carrier==TINYVM_CARRIER_I32&&args[1].carrier==TINYVM_CARRIER_I32){int (*function)(int,int)=NULL;*(void **)(&function)=dlsym(library,"getpriority");if(function){*out=(TinyvmValue){TINYVM_CARRIER_I32,(uint64_t)(int64_t)function((int32_t)args[0].bits,(int32_t)args[1].bits),true};ok=true;}}
    if(!ok&&!exact_failure)*fault="no exact typed runtime thunk for import";
    dlclose(library);
    return ok;
}
