#include <tinyvm/runtime_provider.h>

#include <dlfcn.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static bool authorized(const char *path,const TinyvmImport *x){if(!path)return false;FILE *f=fopen(path,"r");if(!f)return false;char expected[512],legacy[512],line[512];snprintf(expected,sizeof expected,"allow %s %s %s %s %s %s",x->library,x->symbol,x->convention,x->effect,x->parameters,x->result);snprintf(legacy,sizeof legacy,"allow %s %s %s %s",x->library,x->symbol,x->convention,x->effect);bool found=false;while(fgets(line,sizeof line,f)){line[strcspn(line,"\r\n")]=0;if(strcmp(line,expected)==0||(!strcmp(x->parameters,"none")&&!strcmp(line,legacy))){found=true;break;}}fclose(f);return found;}
static const TinyvmString *string_by_id(const TinyvmArtifactV2 *a,uint64_t id){for(size_t i=0;i<a->string_count;++i)if(a->strings[i].id==id)return &a->strings[i];return NULL;}
static const char *string_argument(const TinyvmArtifactV2 *a,const TinyvmRuntimeProvider *provider,uint64_t handle,char **owned){const uint64_t tag=handle>>56,id=handle&UINT64_C(0x00ffffffffffffff);if(tag==1){const TinyvmString *value=string_by_id(a,id);if(!value)return NULL;*owned=malloc(value->length+1);if(!*owned)return NULL;memcpy(*owned,value->bytes,value->length);(*owned)[value->length]=0;return *owned;}if(tag==3&&id<provider->argument_count)return provider->arguments[id];return NULL;}
bool tinyvm_runtime_provider_preflight(const TinyvmRuntimeProvider *provider,const TinyvmArtifactV2 *artifact,const char **fault){if(!provider||!provider->policy_path){*fault="import artifact has no active policy";return false;}for(size_t i=0;i<artifact->import_count;++i)if(!authorized(provider->policy_path,&artifact->imports[i])){*fault="active policy does not authorize every exact import tuple";return false;}return true;}
bool tinyvm_runtime_provider_resolve(void *user,const TinyvmArtifactV2 *a,const TinyvmImport *x,const TinyvmValue *args,size_t count,TinyvmValue *out,const char **fault){
    TinyvmRuntimeProvider *provider=user;
    if(!provider||!authorized(provider->policy_path,x)){*fault="active policy does not authorize exact import tuple";return false;}
    if(strcmp(x->library,"libc.so.6")||strcmp(x->convention,"c")){*fault="runtime provider does not admit import authority";return false;}
    void *library=dlopen(x->library,RTLD_NOW|RTLD_LOCAL);if(!library){*fault="authorized runtime library is unavailable";return false;}bool ok=false;
    if(!strcmp(x->contract,"libc")&&!strcmp(x->effect,"pure")&&!strcmp(x->symbol,"abs")&&!strcmp(x->parameters,"c_int")&&!strcmp(x->result,"c_int")&&count==1&&args[0].carrier==TINYVM_CARRIER_I32){int (*function)(int)=NULL;*(void **)(&function)=dlsym(library,"abs");if(function){const int value=function((int32_t)args[0].bits);*out=(TinyvmValue){TINYVM_CARRIER_I32,(uint64_t)(int64_t)value,true};ok=true;}}
    else if(!strcmp(x->contract,"libc")&&!strcmp(x->effect,"pure")&&!strcmp(x->symbol,"labs")&&!strcmp(x->parameters,"c_long")&&!strcmp(x->result,"c_long")&&count==1&&args[0].carrier==TINYVM_CARRIER_I64){long (*function)(long)=NULL;*(void **)(&function)=dlsym(library,"labs");if(function){*out=(TinyvmValue){TINYVM_CARRIER_I64,(uint64_t)(int64_t)function((long)(int64_t)args[0].bits),true};ok=true;}}
    else if(!strcmp(x->contract,"libc")&&!strcmp(x->effect,"pure")&&!strcmp(x->symbol,"strlen")&&!strcmp(x->parameters,"c_string")&&!strcmp(x->result,"c_size_t")&&count==1&&args[0].carrier==TINYVM_CARRIER_OPAQUE_HANDLE){size_t (*function)(const char *)=NULL;*(void **)(&function)=dlsym(library,"strlen");char *owned=NULL;const char *value=string_argument(a,provider,args[0].bits,&owned);if(function&&value){*out=(TinyvmValue){TINYVM_CARRIER_I64,function(value),true};ok=true;}free(owned);}
    else if(!strcmp(x->contract,"libc")&&!strcmp(x->effect,"io")&&!strcmp(x->symbol,"puts")&&(!strcmp(x->parameters,"c_string")||!strcmp(x->parameters,"Text"))&&!strcmp(x->result,"c_int")&&count==1&&args[0].carrier==TINYVM_CARRIER_OPAQUE_HANDLE){int (*function)(const char *)=NULL;*(void **)(&function)=dlsym(library,"puts");char *owned=NULL;const char *value=string_argument(a,provider,args[0].bits,&owned);if(function&&value){*out=(TinyvmValue){TINYVM_CARRIER_I32,(uint64_t)(int64_t)function(value),true};ok=true;}free(owned);}
    else if((!strcmp(x->contract,"kernel")||!strcmp(x->contract,"linux"))&&!strcmp(x->effect,"readonly")&&!strcmp(x->parameters,"none")&&!strcmp(x->result,"c_int")&&count==0&&(!strcmp(x->symbol,"getpid")||!strcmp(x->symbol,"getuid")||!strcmp(x->symbol,"getgid")||!strcmp(x->symbol,"geteuid")||!strcmp(x->symbol,"getegid")||!strcmp(x->symbol,"getppid")||!strcmp(x->symbol,"getpgrp"))){int (*function)(void)=NULL;*(void **)(&function)=dlsym(library,x->symbol);if(function){*out=(TinyvmValue){TINYVM_CARRIER_I32,(uint64_t)(int64_t)function(),true};ok=true;}}
    else if((!strcmp(x->contract,"kernel")||!strcmp(x->contract,"linux"))&&!strcmp(x->effect,"readonly")&&!strcmp(x->parameters,"c_int")&&!strcmp(x->result,"c_int")&&count==1&&args[0].carrier==TINYVM_CARRIER_I32&&(!strcmp(x->symbol,"getpgid")||!strcmp(x->symbol,"getsid"))){int (*function)(int)=NULL;*(void **)(&function)=dlsym(library,x->symbol);if(function){*out=(TinyvmValue){TINYVM_CARRIER_I32,(uint64_t)(int64_t)function((int32_t)args[0].bits),true};ok=true;}}
    else if((!strcmp(x->contract,"kernel")||!strcmp(x->contract,"linux"))&&!strcmp(x->effect,"readonly")&&!strcmp(x->symbol,"getpriority")&&!strcmp(x->parameters,"c_int,c_int")&&!strcmp(x->result,"c_int")&&count==2&&args[0].carrier==TINYVM_CARRIER_I32&&args[1].carrier==TINYVM_CARRIER_I32){int (*function)(int,int)=NULL;*(void **)(&function)=dlsym(library,"getpriority");if(function){*out=(TinyvmValue){TINYVM_CARRIER_I32,(uint64_t)(int64_t)function((int32_t)args[0].bits,(int32_t)args[1].bits),true};ok=true;}}
    if(!ok)*fault="no exact typed runtime thunk for import";
    dlclose(library);
    return ok;
}
